name: task_managment_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.2
  pin_code_fields: ^8.0.1
  email_validator: ^3.0.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  image_picker: ^1.2.1
  provider: ^6.1.5+1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons :
  android: "launcher_icon"
  ios: true
  image_path : "assets/images/logo.png"

flutter:

  uses-material-design: true
  assets:
    - assets/images/